name: Test CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Run tests
        run: |
          git submodule sync
          chmod +x runAllTests.sh
          ./runAllTests.sh
          
